db_conn: "postgres://db_user:db_password@127.0.0.1:5432/db_name" # строка соединения с БД
address: ":8080"                                                 # адрес HTTP сервера
threads: 500                                                     # количество потоков для обработки списка RSS-лент
source_timeout: 10s                                              # таймаут сервера RSS-ленты